function L = metric_labels()
%METRIC_LABELS Display names of the state-level metrics (field names of W).
L = struct( ...
    'states',        'States (1:1)', ...
    'area',          'Area', ...
    'population',    'Population', ...
    'ep_seats',      'EP seats', ...
    'gdp_eur',       'GDP (EUR)', ...
    'gdp_pps',       'GDP (PPS)', ...
    'council_votes', 'Council votes', ...
    'military',      'Military spending', ...
    'debt',          'Government debt', ...
    'net_payers',    'Net payers (EU budget)', ...
    'net_receivers', 'Net receivers (EU budget)');
end
